#!/usr/bin/env bash
# dd other subdomains
# Bash script that will display information about subdomains.

dns_information () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  dns_information "$1" "www"
  dns_information "$1" "lb-01"
  dns_information "$1" "web-01"
  dns_information "$1" "web-02"
elif [ "$#" == 2 ]
then
  dns_information "$1" "$2"
fi
