#!/usr/bin/env bash
# Create a script to install and configure HAProxy
# Configure HAProxy to send traffic to web-01 and web-02 servers
# use a roundrobin algorithm

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  fady_frontend
        bind *:80
        mode http
        default_backend fady_backend
backend fady_backend
        balance roundrobin
        server 806587-web-01 100.26.156.247:80 check
        server 806587-web-02 23.22.95.84:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
