#!/usr/bin/env bash
# Installs HAProxy version 2.8
# using a round-robin algorithm.
# Port: 80

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get -y install haproxy=2.8.\*

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 806587-web-01 35.153.93.28:80 check\n\tserver 806587-web-02 3.90.84.209:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
