#!/usr/bin/env bash
# This is to print using while loop and then "hi" on the 9th

var_1="Best School"
var_2="Hi"
i="0"
while [ $i -lt 10 ]; do
	if [ $i -eq 9 ]; then
		echo "$var_2"
	fi
	echo "$var_1"
	((i++))
done
