#!/usr/bin/env bash
# This is to print using while loop and then "hi" on the 9th

var_1="Best School"
var_2="bad luck"
var_3="good luck"
i="0"
while [ $i -lt 10 ]; do
	if [ $i -eq 3 ]; then
		echo "$var_2"
	elif [ $i -eq 7 ]; then
		echo "$var_3"
	else
		echo "$var_1"
	fi
	((i++))
done
