#!/usr/bin/env bash
# This is to print using while loop
#The content of the current directory
#In a list format
#only the part of the name after the first dash is displ

list=$(ls)

for i in $list; 
	do echo "$i" | cut -d '-' -f 2
done
